{% set name = "sglang" %}
{% set version = "0.4.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sglang-{{ version }}.tar.gz
  sha256: 4234620aed05b16bade00fa6de3b3e6e9a0afb0f4784bf334164f91fe62a1662

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0
    - wheel
    - pip
  run:
    - python >=3.8
    - aiohttp
    - requests
    - tqdm
    - numpy
    - ipython
    - setproctitle  # 
# Extra: srt_xpu
    - sglang  # 
# Extra: anthropic
    - anthropic >=0.20.0  # 
# Extra: srt_cpu
    - einops  # 
# Extra: blackwell
    - sgl-kernel
    - pytorch ==2.7.1
    - torchaudio ==2.7.1
    - torchvision ==0.22.1
    - cuda-python
    - flashinfer_python ==0.2.7.post1  # 
# Extra: decord
    - decord  # 
# Extra: litellm
    - litellm >=1.0.0  # 
# Extra: openai
    - openai >=1.0
    - tiktoken  # 
# Extra: runtime_common
    - blobfile ==3.0.0
    - python-build
    - compressed-tensors
    - datasets
    - fastapi
    - hf_transfer
    - huggingface_hub
    - interegular
    - llguidance >=0.7.11,<0.8.0
    - modelscope
    - msgspec
    - ninja
    - orjson
    - outlines ==0.1.11
    - packaging
    - partial_json_parser
    - pillow
    - prometheus-client >=0.20.0
    - psutil
    - pydantic
    - pynvml
    - python-multipart
    - pyzmq >=25.1.2
    - soundfile ==0.13.1
    - scipy
    - torchao ==0.9.0
    - transformers ==4.53.0
    - timm ==1.0.16
    - uvicorn
    - uvloop
    - xgrammar ==0.1.19  # 
# Extra: srt
    - sgl-kernel ==0.2.4  # 
# Extra: srt_hip
    - pytorch
    - vllm ==0.6.7.dev2  # 
# Extra: test
    - accelerate
    - jsonlines
    - matplotlib-base
    - pandas
    - peft
    - sentence_transformers  # 
# Extra: torch_memory_saver
    - torch_memory_saver >=0.0.8

test:
  imports:
    - sglang
  commands:
    - pip check
  requires:
    - pip

about:
  summary: SGLang is yet another fast serving framework for large language models and vision language models.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - shermansiu
