context:
  name: sglang
  version: "0.4.9"
  use_cuda: ${{ cuda_compiler_version != "None" }}

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/sglang-${{ version }}.tar.gz
  sha256: 4234620aed05b16bade00fa6de3b3e6e9a0afb0f4784bf334164f91fe62a1662

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0
    - wheel
    - pip
  run:
  # Includes: srt, litellm, runtime_common
    - python >=3.8
    - aiohttp
    - blobfile ==3.0.0
    - compressed-tensors
    - datasets
    - fastapi
    - hf_transfer
    - huggingface_hub
    - interegular
    - ipython
    - litellm >=1.0.0
    - llguidance >=0.7.11,<0.8.0
    - modelscope
    - msgspec
    - ninja
    - orjson
    - numpy
    - outlines ==0.1.11
    - packaging
    - partial_json_parser
    - pillow
    - prometheus-client >=0.20.0
    - psutil
    - pydantic
    - pynvml
    - python-build
    - python-multipart
    - pyzmq >=25.1.2
    - soundfile ==0.13.1
    - requests
    - scipy
    - setproctitle
    - sgl-kernel ==0.2.4
    - torchao ==0.9.0
    - tqdm
    - transformers ==4.53.0
    - timm ==1.0.16
    - uvicorn
    - uvloop
    - xgrammar ==0.1.19
    - if: use_cuda
      then:
        - cuda-version ==${{ cuda_compiler_version }}
        - cuda-python
        - flashinfer_python ==0.2.7.post1
        - pytorch ==2.7.1
        - torchaudio ==2.7.1
        - torchvision ==0.22.1
      else:
        - einops

test:
  - python:
    imports:
    - sglang
    pip_check: true

about:
  homepage: https://github.com/sgl-project/sglang
  summary: SGLang is yet another fast serving framework for large language models and vision language models.
  license: Apache-2.0
  license_file: LICENSE
  documentation: https://docs.sglang.ai/

extra:
  recipe-maintainers:
    - shermansiu
